// Generated by Wrangler on Thu Nov 07 2024 05:39:42 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	WEBSOCKET: DurableObjectNamespace<import("./src/index").WebSocketServer>;
}
